// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: ricartAgrawala.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ricartagrawala_Request_FullMethodName = "/ricartAgrawala.Ricartagrawala/Request"
	Ricartagrawala_Reply_FullMethodName   = "/ricartAgrawala.Ricartagrawala/Reply"
)

// RicartagrawalaClient is the client API for Ricartagrawala service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartagrawalaClient interface {
	// En node beder alle andre om tilladelse til CS
	Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*Ack, error)
	// Tilladelse gives eksplicit via Reply
	Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Ack, error)
}

type ricartagrawalaClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartagrawalaClient(cc grpc.ClientConnInterface) RicartagrawalaClient {
	return &ricartagrawalaClient{cc}
}

func (c *ricartagrawalaClient) Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Ricartagrawala_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartagrawalaClient) Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Ricartagrawala_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartagrawalaServer is the server API for Ricartagrawala service.
// All implementations must embed UnimplementedRicartagrawalaServer
// for forward compatibility.
type RicartagrawalaServer interface {
	// En node beder alle andre om tilladelse til CS
	Request(context.Context, *RequestMsg) (*Ack, error)
	// Tilladelse gives eksplicit via Reply
	Reply(context.Context, *ReplyMsg) (*Ack, error)
	mustEmbedUnimplementedRicartagrawalaServer()
}

// UnimplementedRicartagrawalaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartagrawalaServer struct{}

func (UnimplementedRicartagrawalaServer) Request(context.Context, *RequestMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRicartagrawalaServer) Reply(context.Context, *ReplyMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedRicartagrawalaServer) mustEmbedUnimplementedRicartagrawalaServer() {}
func (UnimplementedRicartagrawalaServer) testEmbeddedByValue()                        {}

// UnsafeRicartagrawalaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartagrawalaServer will
// result in compilation errors.
type UnsafeRicartagrawalaServer interface {
	mustEmbedUnimplementedRicartagrawalaServer()
}

func RegisterRicartagrawalaServer(s grpc.ServiceRegistrar, srv RicartagrawalaServer) {
	// If the following call pancis, it indicates UnimplementedRicartagrawalaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ricartagrawala_ServiceDesc, srv)
}

func _Ricartagrawala_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartagrawalaServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ricartagrawala_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartagrawalaServer).Request(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ricartagrawala_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartagrawalaServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ricartagrawala_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartagrawalaServer).Reply(ctx, req.(*ReplyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Ricartagrawala_ServiceDesc is the grpc.ServiceDesc for Ricartagrawala service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ricartagrawala_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricartAgrawala.Ricartagrawala",
	HandlerType: (*RicartagrawalaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Ricartagrawala_Request_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _Ricartagrawala_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ricartAgrawala.proto",
}
