// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ricartAgrawala.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Lamport-tid ved udsendelse
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`      // valgfrit (fx "req")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	mi := &file_ricartAgrawala_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ricartAgrawala_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_ricartAgrawala_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMsg) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *RequestMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RequestMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Lamport-tid ved udsendelse af reply
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`      // valgfrit (fx "ok")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMsg) Reset() {
	*x = ReplyMsg{}
	mi := &file_ricartAgrawala_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsg) ProtoMessage() {}

func (x *ReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ricartAgrawala_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsg.ProtoReflect.Descriptor instead.
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return file_ricartAgrawala_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMsg) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ReplyMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReplyMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ricartAgrawala_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ricartAgrawala_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ricartAgrawala_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_ricartAgrawala_proto protoreflect.FileDescriptor

const file_ricartAgrawala_proto_rawDesc = "" +
	"\n" +
	"\x14ricartAgrawala.proto\x12\x0ericartAgrawala\"a\n" +
	"\n" +
	"RequestMsg\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"_\n" +
	"\bReplyMsg\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x84\x01\n" +
	"\x0eRicartagrawala\x12:\n" +
	"\aRequest\x12\x1a.ricartAgrawala.RequestMsg\x1a\x13.ricartAgrawala.Ack\x126\n" +
	"\x05Reply\x12\x18.ricartAgrawala.ReplyMsg\x1a\x13.ricartAgrawala.AckBpZngithub.com/Group-GW-Distributed-Systems/Implementation-of-Ricart-Argawala/blob/main/grpc/ricart-argawala.protob\x06proto3"

var (
	file_ricartAgrawala_proto_rawDescOnce sync.Once
	file_ricartAgrawala_proto_rawDescData []byte
)

func file_ricartAgrawala_proto_rawDescGZIP() []byte {
	file_ricartAgrawala_proto_rawDescOnce.Do(func() {
		file_ricartAgrawala_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ricartAgrawala_proto_rawDesc), len(file_ricartAgrawala_proto_rawDesc)))
	})
	return file_ricartAgrawala_proto_rawDescData
}

var file_ricartAgrawala_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ricartAgrawala_proto_goTypes = []any{
	(*RequestMsg)(nil), // 0: ricartAgrawala.RequestMsg
	(*ReplyMsg)(nil),   // 1: ricartAgrawala.ReplyMsg
	(*Ack)(nil),        // 2: ricartAgrawala.Ack
}
var file_ricartAgrawala_proto_depIdxs = []int32{
	0, // 0: ricartAgrawala.Ricartagrawala.Request:input_type -> ricartAgrawala.RequestMsg
	1, // 1: ricartAgrawala.Ricartagrawala.Reply:input_type -> ricartAgrawala.ReplyMsg
	2, // 2: ricartAgrawala.Ricartagrawala.Request:output_type -> ricartAgrawala.Ack
	2, // 3: ricartAgrawala.Ricartagrawala.Reply:output_type -> ricartAgrawala.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ricartAgrawala_proto_init() }
func file_ricartAgrawala_proto_init() {
	if File_ricartAgrawala_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ricartAgrawala_proto_rawDesc), len(file_ricartAgrawala_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ricartAgrawala_proto_goTypes,
		DependencyIndexes: file_ricartAgrawala_proto_depIdxs,
		MessageInfos:      file_ricartAgrawala_proto_msgTypes,
	}.Build()
	File_ricartAgrawala_proto = out.File
	file_ricartAgrawala_proto_goTypes = nil
	file_ricartAgrawala_proto_depIdxs = nil
}
